/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#0a0a0b',
        surface: '#111113',
        's2': '#161618',
        's3': '#1c1c1f',
        border: '#1f1f23',
        'border-subtle': '#161618',
        primary: '#f0f0f2',
        muted: '#6b6b7b',
        dim: '#3a3a45',
        accent: '#6366f1',
        'accent-dim': '#312e81',
        'score-high': '#22c55e',
        'score-mid': '#eab308',
        'score-low': '#f97316',
        'score-fail': '#ef4444',
        'green': '#22c55e',
        'green-dim': '#14532d',
        'yellow': '#eab308',
        'red': '#ef4444',
        'red-dim': '#450a0a',
        'blue': '#3b82f6',
        'purple': '#a855f7',
        'cyan': '#06b6d4',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['10px', '14px'],
        'xs': ['11px', '16px'],
        'sm': ['12px', '18px'],
        'base': ['13px', '20px'],
        'md': ['14px', '20px'],
        'lg': ['15px', '22px'],
        'xl': ['17px', '24px'],
        '2xl': ['20px', '28px'],
        '3xl': ['24px', '32px'],
      },
    },
  },
  plugins: [],
}
